/**
 * destination-map.js
 * ----------------------------------------------------------------
 * File EKSTENSI untuk Page 2 (summon.html).
 *
 * Ini adalah "kamus" (dictionary) yang memetakan setiap Nama pada
 * data API ke sebuah URL tujuan. Saat dadu / summon di Page 2 jatuh
 * pada sebuah nama, summon.html akan mencari nama tersebut di kamus
 * ini dan mengarahkan (redirect) pengguna ke URL yang sesuai.
 *
 * CARA PAKAI:
 *  1. Isi setiap value "url" yang masih kosong dengan URL tujuan,
 *     contoh:  "Bagpipe": { id: 1, url: "https://contoh.com/bagpipe" }
 *  2. Nama yang url-nya masih kosong akan otomatis dianggap "belum
 *     ada tujuan" -> Page 2 hanya menampilkan hasil dadu tanpa redirect.
 *  3. Jangan mengubah nama variabel DESTINATION_MAP, cukup isi field
 *     "url" saja. Field "id" hanya referensi ke id data di API.
 * ----------------------------------------------------------------
 */

const DESTINATION_MAP = {
  "Bagpipe": { id: 1, url: "" },
  "Blaze": { id: 2, url: "" },
  "Astesia": { id: 3, url: "" },
  "Kirigaya Suguha": { id: 4, url: "" },
  "Eunectes": { id: 5, url: "" },
  "Eyjafjalla": { id: 6, url: "" },
  "Feater": { id: 7, url: "" },
  "Franka": { id: 8, url: "" },
  "Gravel": { id: 9, url: "" },
  "Kal'tsit": { id: 10, url: "" },
  "Mudrock": { id: 11, url: "" },
  "Nian": { id: 12, url: "" },
  "Perfumer": { id: 13, url: "" },
  "Platinum": { id: 14, url: "" },
  "Pramanix": { id: 15, url: "" },
  "Provence": { id: 16, url: "" },
  "Saria": { id: 17, url: "" },
  "Shining": { id: 18, url: "" },
  "Siege": { id: 19, url: "" },
  "Skadi": { id: 20, url: "" },
  "W (Wis'adel)": { id: 21, url: "" },
  "Weedy": { id: 22, url: "" },
  "Ryza": { id: 23, url: "" },
  "Agir": { id: 24, url: "" },
  "Amagi": { id: 25, url: "" },
  "Belfast": { id: 26, url: "" },
  "Cheshire": { id: 27, url: "" },
  "Cygnet": { id: 28, url: "" },
  "Elbe": { id: 29, url: "" },
  "Enterprise": { id: 30, url: "" },
  "Formidable": { id: 31, url: "" },
  "Hindenburg": { id: 32, url: "" },
  "Implacable": { id: 33, url: "" },
  "Kashino": { id: 34, url: "" },
  "KMS Roon": { id: 35, url: "" },
  "Kronstadt": { id: 36, url: "" },
  "Lexington": { id: 37, url: "" },
  "Long Island": { id: 38, url: "" },
  "New Jersey": { id: 39, url: "" },
  "Perseus": { id: 40, url: "" },
  "Pola": { id: 41, url: "" },
  "Prinz Heinrich": { id: 42, url: "" },
  "Reno": { id: 43, url: "" },
  "Shokaku": { id: 44, url: "" },
  "St. Louis": { id: 45, url: "" },
  "Takao": { id: 46, url: "" },
  "Taihou": { id: 47, url: "" },
  "Yorktown": { id: 48, url: "" },
  "Zara": { id: 49, url: "" },
  "Akane": { id: 50, url: "" },
  "Amau Ako": { id: 51, url: "" },
  "Aru (Rikuhachima Aru)": { id: 52, url: "" },
  "Asuma Toki": { id: 53, url: "" },
  "Ayane": { id: 54, url: "" },
  "Eimi": { id: 55, url: "" },
  "Fuuka": { id: 56, url: "" },
  "Hanako": { id: 57, url: "" },
  "Hanekawa Hasumi": { id: 58, url: "" },
  "Haruka": { id: 59, url: "" },
  "Ichika": { id: 60, url: "" },
  "Ichinose Asuna": { id: 61, url: "" },
  "Iroha": { id: 62, url: "" },
  "Karin": { id: 63, url: "" },
  "Kasumi": { id: 64, url: "" },
  "Kazusa": { id: 65, url: "" },
  "Kirino": { id: 66, url: "" },
  "Kisaki": { id: 67, url: "" },
  "Kokona": { id: 68, url: "" },
  "Kuroko": { id: 69, url: "" },
  "Marina": { id: 70, url: "" },
  "Mayoi Shigure": { id: 71, url: "" },
  "Mine": { id: 72, url: "" },
  "Mitsuki": { id: 73, url: "" },
  "Noa": { id: 74, url: "" },
  "Profesor Niyaniya": { id: 75, url: "" },
  "Rio Tsukatsuki": { id: 76, url: "" },
  "Ryuge Kisaki": { id: 77, url: "" },
  "Saki": { id: 78, url: "" },
  "Serina": { id: 79, url: "" },
  "Shiroko": { id: 80, url: "" },
  "Tsubaki": { id: 81, url: "" },
  "Urakawa Hanako": { id: 82, url: "" },
  "Wakamo": { id: 83, url: "" },
  "Mari": { id: 84, url: "" },
  "BB": { id: 85, url: "" },
  "Boudica": { id: 86, url: "" },
  "Bradamante": { id: 87, url: "" },
  "Da Vinci": { id: 88, url: "" },
  "Helena": { id: 89, url: "" },
  "Jack": { id: 90, url: "" },
  "Martha": { id: 91, url: "" },
  "Mash": { id: 92, url: "" },
  "Mikoto (Fate)": { id: 93, url: "" },
  "Musashi": { id: 94, url: "" },
  "Shikibu": { id: 95, url: "" },
  "Stheno": { id: 96, url: "" },
  "Suzuka Gozen": { id: 97, url: "" },
  "Tomoe": { id: 98, url: "" },
  "Zenobia": { id: 99, url: "" },
  "Tifa Lockhart": { id: 100, url: "" },
  "Amber": { id: 101, url: "" },
  "Ayaka": { id: 102, url: "" },
  "Barbara": { id: 103, url: "" },
  "Citlali": { id: 104, url: "" },
  "Eula": { id: 105, url: "" },
  "Fatui": { id: 106, url: "" },
  "Fischl": { id: 107, url: "" },
  "Furina": { id: 108, url: "" },
  "Furina T18": { id: 109, url: "" },
  "Ganyu": { id: 110, url: "" },
  "Keqing": { id: 111, url: "" },
  "Kokomi": { id: 112, url: "" },
  "Lisa": { id: 113, url: "" },
  "Lumine": { id: 114, url: "" },
  "Lynette": { id: 115, url: "" },
  "Nilou": { id: 116, url: "" },
  "Noelle": { id: 117, url: "" },
  "Raiden": { id: 118, url: "" },
  "Yae Miko": { id: 119, url: "" },
  "Yelan": { id: 120, url: "" },
  "Darjeeling": { id: 121, url: "" },
  "Miho Nishizumi": { id: 122, url: "" },
  "HK416": { id: 123, url: "" },
  "Sword Maiden": { id: 124, url: "" },
  "Narmaya": { id: 125, url: "" },
  "Ceres Fauna": { id: 126, url: "" },
  "Aponia": { id: 127, url: "" },
  "Bronya Zaychik": { id: 128, url: "" },
  "Durandal": { id: 129, url: "" },
  "Elysia": { id: 130, url: "" },
  "Fu Hua": { id: 131, url: "" },
  "Griseo": { id: 132, url: "" },
  "Herrscher of Void": { id: 133, url: "" },
  "Kaslana": { id: 134, url: "" },
  "Kongming": { id: 135, url: "" },
  "Mei": { id: 136, url: "" },
  "Mobius": { id: 137, url: "" },
  "Rita": { id: 138, url: "" },
  "Rozaliya": { id: 139, url: "" },
  "Yae Sakura": { id: 140, url: "" },
  "Black Swan": { id: 141, url: "" },
  "Herta": { id: 142, url: "" },
  "Jingliu": { id: 143, url: "" },
  "Kafka": { id: 144, url: "" },
  "SAM": { id: 145, url: "" },
  "Ahri": { id: 146, url: "" },
  "Ashe": { id: 147, url: "" },
  "Asida": { id: 148, url: "" },
  "Asina": { id: 149, url: "" },
  "Baal": { id: 150, url: "" },
  "Iblis": { id: 151, url: "" },
  "KSVIII": { id: 152, url: "" },
  "Rozetta": { id: 153, url: "" },
  "Ruchee": { id: 154, url: "" },
  "Satan": { id: 155, url: "" },
  "Ayase Eli": { id: 156, url: "" },
  "Maki": { id: 157, url: "" },
  "Chika": { id: 158, url: "" },
  "Hanamaru": { id: 159, url: "" },
  "Kanan": { id: 160, url: "" },
  "Yoshiko Tsushima": { id: 161, url: "" },
  "You Watanabe": { id: 162, url: "" },
  "Samus Aran": { id: 163, url: "" },
  "Ade": { id: 164, url: "" },
  "Alice": { id: 165, url: "" },
  "Anis": { id: 166, url: "" },
  "Bay": { id: 167, url: "" },
  "Blanc": { id: 168, url: "" },
  "Cinderella": { id: 169, url: "" },
  "Clay": { id: 170, url: "" },
  "Crown": { id: 171, url: "" },
  "Dolla": { id: 172, url: "" },
  "Dorothy": { id: 173, url: "" },
  "Eleg": { id: 174, url: "" },
  "Helm": { id: 175, url: "" },
  "Ludmilla": { id: 176, url: "" },
  "Marciana": { id: 177, url: "" },
  "Mary": { id: 178, url: "" },
  "Modernia": { id: 179, url: "" },
  "Neon": { id: 180, url: "" },
  "Noir": { id: 181, url: "" },
  "Privaty": { id: 182, url: "" },
  "Rosanna": { id: 183, url: "" },
  "Rupee": { id: 184, url: "" },
  "Soda": { id: 185, url: "" },
  "Tia": { id: 186, url: "" },
  "Viper": { id: 187, url: "" },
  "Volume": { id: 188, url: "" },
  "Alex": { id: 189, url: "" },
  "Arch Demon": { id: 190, url: "" },
  "Historia": { id: 191, url: "" },
  "Nozomi": { id: 192, url: "" },
  "Akarin": { id: 193, url: "" },
  "Chieru": { id: 194, url: "" },
  "Hatsune": { id: 195, url: "" },
  "Misato": { id: 196, url: "" },
  "Neneka": { id: 197, url: "" },
  "Pecorine": { id: 198, url: "" },
  "Sumi": { id: 199, url: "" },
  "Yui": { id: 200, url: "" },
  "Yuni": { id: 201, url: "" },
  "Rem": { id: 202, url: "" },
  "Chris": { id: 203, url: "" },
  "Kohinata Miku": { id: 204, url: "" },
  "Tachibana Hibiki": { id: 205, url: "" },
  "Tsukuyomi Shirabe": { id: 206, url: "" },
  "Yukine Chris": { id: 207, url: "" },
  "Zelda": { id: 208, url: "" },
  "Flandre Scarlet": { id: 209, url: "" },
  "Ran": { id: 210, url: "" },
  "Reimu Hakurei": { id: 211, url: "" },
  "Yukari Yakumo": { id: 212, url: "" },
  "Yuyuko Saigyouji": { id: 213, url: "" },
  "Mythra": { id: 214, url: "" },
  "Pneuma": { id: 215, url: "" },
  "Pyra": { id: 216, url: "" },
  "Dark Magician Girl": { id: 217, url: "" },
  "I:P Masquerena": { id: 218, url: "" },
  "Magistus of Verre – Rilliona": { id: 219, url: "" },
};

// Jangan hapus baris di bawah ini - dibutuhkan agar summon.html bisa membaca kamus ini
if (typeof window !== "undefined") window.DESTINATION_MAP = DESTINATION_MAP;
